# Generated by Django 5.0.6 on 2025-04-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Mixed Food', 'Mixed Food'), ('Suit', 'Suit'), ('Spaghetti', 'Spaghetti'), ('Add', 'Add'), ('Drink', 'Drink')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
