# Generated by Django 5.0.6 on 2025-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0003_product_category_product_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Mixed Food', 'Mixed Food'), ('Suit', 'Suit'), ('Steak', 'Steak'), ('Spaghetti', 'Spaghetti'), ('Add', 'Add'), ('Drink', 'Drink')], max_length=255, null=True),
        ),
    ]
