# Generated by Django 5.0.6 on 2025-04-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
