# Generated by Django 5.0.6 on 2025-04-11 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0005_remove_order_address_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
