# Generated by Django 5.0.6 on 2025-04-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0007_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
    ]
